### ISSUE TITLE
Running pretrained_models download error 

### ISSUE THREAD

**Issue by yumikim381** [zhuhao-nju/mofanerf#15]
pretrained_models.tar.gz has already been downloaded.
pretrained models have been extracted to ./logs/
./download_pretrained_models.sh: line 1: due: command not found

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Does anyone else have this error, and know how to resolve it?

**Comment by nqdung2002** [comment]
I have the same issues as you but the bash window exit quickly. It says:

bash: due: command not found
bash: wget: command not found

pretrained_models.tar.gz was not downloaded. Can anyone help me please?

**Comment by nqdung2002** [comment]
Oh I handled it by simply downloaded the pretrained_models.tar.gz from google drive and then extracted to /logs/ folder.
Moreover, remember to replace ("/") to ("\\") in line 89 in create_model_condition.py

**Comment by yumikim381** [comment]
If i do that i get this error : 
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/mofanerf/run_fit.py", line 12, in <module>
    from tools.create_model_condition import create_nerf
  File "/content/gdrive/MyDrive/mofanerf/tools/create_model_condition.py", line 89
    start = int(ckpt_path.split("\")[-1][:-4])
SyntaxError: EOL while scanning string literal

Just to be sure, do you just put the folder "mofanerf_pretrained_model" from pretrained_models.tar.gz (the one downloaded from the link from bash script "https://drive.google.com/u/0/uc?id=1jlhtm8BoChczSMks3WjChQ_SGLXyZ9ka&export=download" )into /log/? And nothing else ?

**Comment by nqdung2002** [comment]
Oh that was my fault
You need to put 2 folders from "mofanerf_pretrained_model" (which are mofanerf_0to300 and refine) **directly** into /log/ (not the big folder "mofanerf_pretrained_model")
And you need to replace  ("/") to ("\\") (2 backward dash)

**Comment by yumikim381** [comment]
Thank you soooooo much for your help, It finally works now!:D

**Comment by nqdung2002** [comment]
Can you refine the fitted result? I don't know how to fix this.
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Downloads\mofanerf-main\mofanerf-main\run_refine.py", line 37, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1043, in __init__
    w.start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\mofanerf-main\mofanerf-main\run_refine.py", line 37, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 17484) exited unexpectedly
`
I found something in run_refine.py line 35. It says "Unresolved reference 'run_engine'". I cannot find where this is

**Comment by yumikim381** [comment]
Heyy running run_refine.py works for me fine..
At the end i didn't change the line 89 in create_model_condition.py
If you want i can give you my google colab notebook:)

**Comment by nqdung2002** [comment]
It would be really really nice. Thank you so much <3

**Comment by yumikim381** [comment]
here you go :)
https://github.com/yumkim381/mofane_run_colab.git
